# Generated by Django 4.1.1 on 2022-12-21 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0003_watchlist_plateform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="plateform",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist",
                to="watchlist_app.streamplatform",
            ),
        ),
    ]
