# Generated by Django 4.1.1 on 2022-12-21 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0005_alter_watchlist_plateform"),
    ]

    operations = [
        migrations.RemoveField(model_name="watchlist", name="plateform",),
    ]
