# Generated by Django 4.1.1 on 2022-12-21 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0006_remove_watchlist_plateform"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="plateform",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist",
                to="watchlist_app.streamplatform",
            ),
            preserve_default=False,
        ),
    ]
